### ISSUE TITLE
Unpredictable behaviour when /org/gnome/shell/overrides/dynamic-workspaces == true

### ISSUE THREAD

**Issue by tomasstorck** [zakkak/workspace-grid#11]
## Description

Things go awry when dynamic workspaces are enabled: the number of workspaces does not match the number that should exist with the current grid specifications. This makes workspace behaviour unpredictable, see screenshot.

Screenshot: 5 dynamic workspaces visible on a 3x3 grid. There are no workspaces accessible beyond 5.
![example-dynamic-workspaces](https://cloud.githubusercontent.com/assets/3627541/9251301/caa46b7a-41d2-11e5-91ac-7e476e90f80c.png)
## Workaround

In order to get things to work as they should,  dynamic workspaces need to be disabled. This can be done by manually setting the correct number via the interface (GNOME Tweak Tool > Workspaces > Static) or by simply running:

```
dconf write /org/gnome/shell/overrides/dynamic-workspaces false
```

Your extension seems smart enough to automatically set the correct number of workspaces in this case.
## Suggested fix

I'm not familiar with your code base, but you seem to manually update the number of workspaces upon changing the grid configuration. You could probably fix this issue by setting /org/gnome/shell/overrides/dynamic-workspaces to false whenever the grid setings are changed.

**Comment by tomasstorck** [comment]
I see you're already aware of this. In `extension.js`, around line 1220:
```
 /* NOTE: in GNOME 3.4, 3.6, 3.8, Meta.prefs_set_num_workspaces has
     * *no effect* if Meta.prefs_get_dynamic_workspaces is true.
     * (see mutter/src/core/screen.c prefs_changed_callback).
     * To *actually* increase/decrease the number of workspaces (to fire
     * notify::n-workspaces), we must use global.screen.append_new_workspace and
     * global.screen.remove_workspace.
     *
     * We could just set org.gnome.shell.overrides.dynamic-workspaces to false
     * but then we can't drag and drop windows between workspaces (supposedly a
     * GNOME 3.4 bug, see the Frippery Static Workspaces extension. Can confirm
     * but cannot find a relevant bug report/fix.)
     * Can confirm the bug in 3.6 too.
     * In 3.8 I appear to be able to drag/drop between workspace but not to
     * drag/drop to create new workspaces (with the placeholder animation),
     * so I'll stick to this method for now.
     */
```
In Gnome Shell 3.16 I can drag-and-drop as much as I like.  Not sure I understand what you mean by "drag/drop to create new workspaces (with the placeholder animation)", as workspaces should be inherently static with this extension, correct?

**Comment by zakkak** [comment]
Unfortunately this is not code I have personally written. This repository is a fork from [bitbucket](https://bitbucket.org/mathematicalcoffee/workspace-grid-gnome-shell-extension) and its purpose is to keep this extension working with the latest GNOME releases.  I will more than happily accept patches that resolve any issues or add new features.
