### ISSUE TITLE
Workspace grid fails after screen lock

### ISSUE THREAD

**Issue by maurimonti** [zakkak/workspace-grid#111]
Hi,
Since this morning, probably after some updates, I found that workspace grid was set off and impossible to restart. Uninstalling and reinstalling solves temporarily the problem until the screen is locked; then the problem arises again.

System: Ubuntu 18.04.1 LTS
Gnome shell version: 3.28.2

Updates that might be related to the issue:
 apt apt-transport-https apt-utils gir1.2-nma-1.0 libapt-inst2.0 libapt-pkg5.0 libnm-gtk0 libnma0 libpoppler-glib8 libpoppler-qt5-1 libpoppler73 libtiff5 network-manager-gnome poppler-utils

Thank you,
Maurizio

**Comment by zakkak** [comment]
I have the same setup and it seems to work fine. Are you using wayland or X11?

**Comment by maurimonti** [comment]
X11, but I just thought of restarting the computer and now everything seems to work back again.
I should've thought this before posting.
Sorry for the waste of time

**Comment by zakkak** [comment]
NP, closing it for now, please reopen if the issue persists.
