### ISSUE TITLE
version 29?

### ISSUE THREAD

**Issue by brianjmurrell** [zakkak/workspace-grid#118]
When I download this extension from https://extensions.gnome.org/extension/484/workspace-grid/ for GNOME 3.30, the version is 29, however when I look at the `metadata.json` for 3.30:

https://github.com/zakkak/workspace-grid/blob/3a06856f8009d3577d7668b1dfd084b1afe82949/src/metadata.json#L1-L14

It says the version is 28.

So where is the code for the version 29 that was uploaded to https://extensions.gnome.org/extension/484/workspace-grid/?

**Comment by zakkak** [comment]
Hello Brian,

I am not sure, but I think that gnome shell extensions updates the version each time you upload something (ignoring the metadata.json you use), this should be the same as the latest release on github. If not, then it should be older and not newer. Sorry for the inconvenience.
