### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by building39** [zakkak/workspace-grid#124]
Installing this extension fails for:

Chrome: Version 79.0.3945.88 (Official Build) (64-bit)
OS: Linux datacat 5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
![Screenshot from 2019-12-21 08-10-22](https://user-images.githubusercontent.com/875327/71308351-736ad000-23c9-11ea-81c2-d90694601ea1.png)
No helpful information seems available

**Comment by boehm-e** [comment]
Same here

**Comment by zakkak** [comment]
This extension is no longer maintained you might want to have a look at https://extensions.gnome.org/extension/1485/workspace-matrix/ (github repo: https://github.com/mzur/gnome-shell-wsmatrix)
