### ISSUE TITLE
Unable to install it on Debian Gnome 3.22.2 (invalid extension)

### ISSUE THREAD

**Issue by b3** [zakkak/workspace-grid#37]
When trying to install the extensions in Gnome 3.22.2 on my Debian Testing (stretch) laptop I get an `invalid extension` message and I cannot install nor use it.

**Comment by AndrewFridley** [comment]
GLib.FileError: Failed to open file '/home/me/.local/share/gnome-shell/extensions/workspace-grid@mathematical.coffee.gmail.com/schemas/gschemas.compiled': open() failed: No such file or directory

Stack trace:
  getSettings@/home/x2/.local/share/gnome-shell/extensions/workspace-grid@mathematical.coffee.gmail.com/convenience.js:78
  WorkspaceGridPrefsWidget<._init@/home/x2/.local/share/gnome-shell/extensions/workspace-grid@mathematical.coffee.gmail.com/prefs.js:65
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  buildPrefsWidget@/home/x2/.local/share/gnome-shell/extensions/workspace-grid@mathematical.coffee.gmail.com/prefs.js:221
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:238
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:376
  @<main>:1
  
I get have the same problem I believe.

**Comment by zakkak** [comment]
So did you try to check if the file `/home/me/.local/share/gnome-shell/extensions/workspace-grid@mathematical.coffee.gmail.com/schemas/gschemas.compiled` is indeed not present?

If it is present what permissions does it have?

Did you try [installing from github](https://github.com/zakkak/workspace-grid-gnome-shell-extension#installation)?

**Comment by b3** [comment]
The file is present on my box with mode 0764.

Since some days the extension seems to *work* almost again (when the grid is not complete unless I create a window in each workspace).

I did not try to install it from github.

**Comment by arist0tl3** [comment]
Hey, just wanted to confirm that this is still an issue.

I tried to upgrade, and it failed and left the extension in the broken state that @AndrewFridley encountered. I tried removing and re-installing from both the extensions page and by using the zip and both ended in the same broken state.

I had a previous zip from about two years ago that still had the gschemas.compiled file in it, so I copied that to the schemas folder in my broken installation and it started working.

**Comment by zakkak** [comment]
So do you think that the `gschemas.compiled` file was broken in your case? Did you try inspecting it before replacing it?

**Comment by arist0tl3** [comment]
No, it was missing in each installation I tried. I saw the schema file that's included in the bundle, but that was the only one.

**Comment by zakkak** [comment]
@arist0tl3 what linux distro and gnome version are you using?

**Comment by alinafdima** [comment]
Hi,

I had a similar issue when I upgraded to Debian 3.22.2. I had been using the extension already, and when I upgraded the extension had an error and I could not enable it any more. Afterwards it disappeared from the Tweak Tool Menu, and whenever I tried installing it from the gnome extension website, it would ask me if I am ok with downloading the extension, I would click yes and then it would do nothing and the switch off again on the website. 

When I went to this location `/home/me/.local/share/gnome-shell/extensions/workspace-grid@mathematical.coffee.gmail.com/schemas/gschemas.compiled` and checked the permissions, it had only read permissions but then changing it to u+x did not seem to help. Afterwards I tried to delete this folder `/home/me/.local/share/gnome-shell/extensions/workspace-grid@mathematical.coffee.gmail.com`, but it told me it was busy. I logged off, deleted the folder and was able to successfully reinstall the extension.

**Comment by paugier** [comment]
I have a similar issue on Gnome 3.22.3.

I try to install the extensions 
- via `gnome-tweak-tool` : invalid extension
- via https://extensions.gnome.org/extension/484/workspace-grid/ : clicking the toggle switch has no effect

```
~/.local/share/gnome-shell/extensions/workspace-grid@mathematical.coffee.gmail.com/schemas$ ls -l
total 8
-rw-r--r-- 1 me all-users  853 Apr  5 10:41 gschemas.compiled
-rw-r--r-- 1 me all-users 3192 Apr  5 10:41 org.gnome.shell.extensions.workspace-grid.gschema.xml
```

Is there a workaround?

How can I get a better error log?

**Comment by paugier** [comment]
Please... Help needed !

**Comment by mqu** [comment]
hello all, I am having same issue as paugier ; I use debian stretch for my desktop with gnome-shell  3.22.3-3

**Comment by zakkak** [comment]
Hello all, I would like to let you know that I cannot personally put effort to maintain the extension for 3.22
If you manage to find a solution please open a PR on the 3.22 branch.

**Comment by mqu** [comment]
this issue is not specific to workspace-grid ; I have same issue with Docker-Integration and many other. May be a specific Debian issue ?

**Comment by zakkak** [comment]
It might have to do with how extensions get installed. Did you try installing manually? (See https://github.com/zakkak/workspace-grid/issues/78#issuecomment-416775946)

**Comment by mqu** [comment]
Hello Zakkak, 

I have been able to install manually workspace-grid extension in my profile. After logout and login again, now the extension work again. Really good news.

- Installed version is number 24 (dev 1.44) with Debian Stretch 9.5, gnome-shell 3.22
- install directory is : ~/.local/share/gnome-shell/extensions/workspace-grid@mathematical.coffee.gmail.com
- seems not to work in system directory /usr/share/gnome-shell/extensions

Install issue seems to be related to Debian Stretch only.

thank you so much for your help. Marc.

**Comment by zakkak** [comment]
Nice, glad you figured it out, it is strange though how this bug hasn't come up before and remains still present in debian :S

Anyway, since it seems unrelated to the extension, as far as I understand at least, I am closing this.

**Comment by mqu** [comment]
a really quick way to install workspacegrid extension manually :
```
ext_inst_dir=~/.local/share/gnome-shell/extensions/workspace-grid@mathematical.coffee.gmail.com
version=v27  # you may choose between 24-27
src="https://extensions.gnome.org/extension-data/workspace-grid%40mathematical.coffee.gmail.com.${version}.shell-extension.zip"

rm -fr $ext_inst_dir
mkdir -p $ext_inst_dir
cd /tmp
wget $src
unzip -d ${ext_inst_dir} /tmp/workspace-grid@mathematical.coffee.gmail.com.${version}.shell-extension.zip
```
