### ISSUE TITLE
Grid lingers after workspace switch

### ISSUE THREAD

**Issue by integrics** [zakkak/workspace-grid#42]
When using ctrl and a cursor key to move to an adjoining workspace, the grid overlay lingers for half a second or so. This is just long enough to be annoying, because you're trying to read that new email that just arrived through the grid. Can the grid be made to disappear the instant the user lifts their finger from the cursor key?

**Comment by zakkak** [comment]
This has to do with the gnome animations. Workspace grid does not alter the time the grid overlay stays on the screen AFAIK.

You can try disabling workspace grid and see if the behaviour is the same.

**Comment by integrics** [comment]
Yes, it still happens with Workspace Grid disabled. I tried setting:

gsettings set org.gnome.desktop.interface enable-animations false

but it had no effect. Suggestions welcome...

**Comment by zakkak** [comment]
Unfortunately I don't know how and if it's possible to disable them or alter their duration.

**Comment by zakkak** [comment]
However, since you are only interested in the gird layout and not all animations you could probably try to:

1. Alter your theme so it makes it completely transparent

or

2. Patch workspace grid to have an option to disable it (not sure how)

**Comment by integrics** [comment]
Hmm, those both sounds complex. I'll put up with it for now. Sorry to disturb you.
