### ISSUE TITLE
Multiple crashes

### ISSUE THREAD

**Issue by juliendangers** [zakkak/workspace-grid#45]
Hello,

I encounter multiple crashes every day when switching between workspaces. Crashes are due to the following errors:

  * ```children[i] is undefined``` https://github.com/zakkak/workspace-grid/blob/3.24/workspace-grid%40mathematical.coffee.gmail.com/myWorkspaceSwitcherPopup.js#L135
  * ```thumbnail is undefined``` https://github.com/zakkak/workspace-grid/blob/3.24/workspace-grid%40mathematical.coffee.gmail.com/extension.js#L836

Gnome version: 3.24
Config:
* 4 rows
* 1 column
* relative workspace switching: On
* wraparound: On
* wrap same row/col: Off
* show worskape label: On

=> Ooops, workspace creation was set to dynamic, might be the problem...

**Comment by zakkak** [comment]
> Ooops, workspace creation was set to dynamic, might be the problem...

Yes usually crashes are caused due to not having static workspaces (and maybe number of workspaces not being equal to rows times columns.

Please see if having it properly set fixes the issue for you and update this issue.

**Comment by juliendangers** [comment]
No problem since dynamic workspace creation was disabled
