### ISSUE TITLE
Inconsistent shortkeys

### ISSUE THREAD

**Issue by Vinno97** [zakkak/workspace-grid#51]
Hi,

I used to be able to press `Ctrl + Alt + Top + Left` to instantly go to the top-left workspace. When I do that now, it only goes to whatever direction I press first. When I press them at exactly the same time, it just does nothing.

`Ctrl + Alt + Top + Right `, `Ctrl + Alt + Bottom + Right ` and `Ctrl + Alt + Bottom + Left ` do work, but they do not have the nice diagonal animation anymore. They just mush the vertical and horizontal animation togeter (it seems) and it only properly shows the end of the last animation.  

This is not a critical bug, but a graphical one that makes the desktop feel less refined and responsive.

I observed this behavior with:
Ubuntu 17.10
GNOME Shell 3.26.2
Workspace Grid 24

**Comment by zakkak** [comment]
This doesn't seem like a workspace grid issue. Maybe a package upgrade caused the behavior change.
