### ISSUE TITLE
Grid is being switched off. Gnome 3.22

### ISSUE THREAD

**Issue by dodiak** [zakkak/workspace-grid#52]
Hi, yesterday suddenly desktop grid stopped to work. Under extensions setting I found out that it is disabled. After enabling nothing happened. Closing and opening gnome-tweak-tool again, the grid was again off. Now instead of 3x3 desktops I have 1x9 :( Any ideas? I know nothing about gnome btw, just thinking to migrate from fvwm ...

**Comment by jglotzer** [comment]
I had exactly same issue with Ubuntu 16.04, GS 3.18.5.

Debugged by running GS from a terminal (gnome-shell -r) and noticing that I got a log message to the effect of:

```
Line 1133 global.screen.workspace_grid is undefined 
```


when this happens.

I added:
```

function modifyNumWorkspaces() {

    //experimental                                                                                      
     if (global.screen.workspace_grid == 'undefined') {
        log("WARNING [workspace-grid]: modifyNumWorkspaces global.screen.workspace_grid was undefined!"\
);
        return;
    }
... function continues ...
```

well can't say that I've seen this message printed yet so probably too soon to know if this is the answer or not.

But I'm pretty sure that at least that the undefined variable at line 1133 is the cause of the extension switching off. I'm no javascript expert or gnome expert so maybe my proposed "solution" is incredibly naive so buyer beware - but I don't imagine it's too risky a change either.

**Comment by rakus** [comment]
Sounds like #33 
Try `ALT-F2`  and `r` to restart GNOME Shell.
