### ISSUE TITLE
Unable to change workspace up/down while app is open

### ISSUE THREAD

**Issue by shaansheikh** [zakkak/workspace-grid#53]
So the ctrl+alt+left/right arrow key allows me to change workspace left and right without issue. However, it seems the workspace up/down shortcut is super+fn+up/down arrow key. This works on the desktop, but when focused on an application, scrolls down the application.

Is there any way to change the shortcut to ctrl+alt+up/down key?

**Comment by rakus** [comment]
Check your GNOME keyboard shortcuts. 
See "Move to workspace above" and "... below" in the section "Navigation".

**Comment by shaansheikh** [comment]
oh, duh. Thanks
