### ISSUE TITLE
Missing keybinding/shortcut for more than 4 workspaces

### ISSUE THREAD

**Issue by ElijahLynn** [zakkak/workspace-grid#54]
I have more than 4 workspaces and in the system keyboard shortcuts it only has a default of 4 and doesn't reflect the new workspace numbers created by workspace-grid. How can I make a keyboard shortcut to switch to these new workspaces?

![screenshot from 2018-03-09 12-34-02](https://user-images.githubusercontent.com/1504756/37228666-373ad484-2396-11e8-9e24-2b34b55fc074.png)

**Comment by Achse** [comment]
Hi, here is my script that I use for inspiration: https://github.com/Achse/desktop-scripts-and-configs/blob/master/gnome-3x3-workspaces.sh 

Basically, you can call command in your terminal like:
```bash
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5 "[\"<Alt>rcaron\"]"
 ```

To assign any bing you like.

**Comment by ElijahLynn** [comment]
@Achse Saweet! I was looking for a while how to switch to workspaces from the command line. This works very well as a workaround for now, thank you.
