### ISSUE TITLE
workspace overview on second monitor

### ISSUE THREAD

**Issue by moritzaugustin** [zakkak/workspace-grid#57]
When using workspace-grid (using Fedora 27's current gnome3) the overview of the workspaces works nicely on the primary screen. However, on my second monitor it is either missing -- or when using in addition another addon [Multi Monitors Add-On by spin83] that second screen windows overview is shown in a long list instead of the same rectangular view as it is organized on the first screen. This behaviour makes (for me) the overview on the second screen unusable since logically the workspaces are distinct but the monitors jointly define the set of windows. 

Even better it would be if the main view would include the workspaces from both, e.g.
W1     W4
V1      V4

W2    W5
V2     V5

W3     W6
V3      V6
... in *one* view for overviewing both monitors at the same time (W*, V* are the workspaces of the first and second screen, respectively).

Is there a possiblity to activate either the first or second variant of rectangular overview also of the second screen's windows?

**Comment by moritzaugustin** [comment]
note that the following issue is opened and includes a screenshot of the current (wrong) behaviour: 
https://github.com/spin83/multi-monitors-add-on/issues/42
it would be great if in this or at their issue the code segment could be identified which is responsible for the current behaviour and should be improved

**Comment by dprada** [comment]
Having the second monitor included in the grid (workspace switcher) would be great!
I have the same problem. When the grid is display only the thumbnail of the left monitor is used to make the grid. 
A grid with Number_of_Columns x Number_of_Monitors x Number_of_Rows is very useful.

**Comment by zakkak** [comment]
@dprada please open a new issue for this FR.

@moritzaugustin regarding the incompatibility with multi-monitors, it is most probably caused because workspace-grid hijacks the workspace slider and I guess multi-monitors creates a completely new slider for the second screen. For now solving this doesn't seem straight forward. There is always the option to make one plugin aware of the other but a more generic approach would be better.
