### ISSUE TITLE
Weird animations on workspace switch

### ISSUE THREAD

**Issue by hassanalinali** [zakkak/workspace-grid#58]
There is a weird animation when I switch the workspace that I showcased below/
I use Ubuntu 17.10 with Gnome Shell 3.26.2 and no other extensions regarding workspaces.
Looks like every time that I hit the last workspace on the left this happends.

If there's anything that I could provide please tell me.

![gif](https://user-images.githubusercontent.com/4151505/37621869-82e0ccc2-2bc0-11e8-840c-fd02c7e833d4.gif)

**Comment by hassanalinali** [comment]
Somehow I've installed 2 of the suggested extensions and one of them changed the appearance and also fixed the bug.

**Comment by zakkak** [comment]
Yes, this is solved by 1 from https://github.com/zakkak/workspace-grid#quirks--known-issues
