### ISSUE TITLE
Highlight is messed up

### ISSUE THREAD

**Issue by Vrondir** [zakkak/workspace-grid#59]
When I restart the shell the highlight is on the right workspace.

![screenshot from 2018-03-23 16-35-39](https://user-images.githubusercontent.com/7314229/37836069-451ee16a-2eba-11e8-996b-8f770a45d4cd.png)

But when I switch on a different workspace the highlight jumps off to the top left corner.

![screenshot from 2018-03-23 16-35-55](https://user-images.githubusercontent.com/7314229/37836694-c7a80b10-2ebb-11e8-83d9-a5a2c2bb1c33.png)

This has been a problem from quite some time now... but it did work before.

**Comment by felipemarinho97** [comment]
I have the same issue on Arch Linux, it appears to be caused by the latest **gjs** version, downgrading this package from <= 1.50.2-1. version may fix it.

**Comment by thekswenson** [comment]
I didn't have this problem until I upgraded to Ubuntu 18.04 from 17.10.

**Comment by JustPerfection** [comment]
I have the same bug on Ubuntu 18.04 GNOME 3.28.1

**Comment by xMordax** [comment]
any news on the bugfix?
