### ISSUE TITLE
Missing left/right shortcuts on Pop!_OS 18.04

### ISSUE THREAD

**Issue by lasseebert** [zakkak/workspace-grid#65]
I have use Workspace Grid some time now and it has worked like a charm :)

I have just reinstalled from Pop!_OS 17.10 to 18.04 and now I'm missing shortcut bindings to move to left/right workspace. Pop!_OS is built on top of Ubuntu.

I have tried to reinstall the extension, but no luck.
Any ideas what to do?

Thanks for a great extension!

**Comment by ssafras** [comment]
For left and right you could write the following on the terminal (you can change the key combo as you wish):

$ gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right "[\"<Super>Right\"]"
$ gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left "[\"<Super>Left\"]"

This worked for me on Ubuntu 18.04 with Gnome.

**Comment by lasseebert** [comment]
Awesome, thanks @ssafras.

In addition, I used `switch-to-workspace-left` and `switch-to-workspace-right`. Works fine.

**Comment by sipdbg2** [comment]
Ubuntu 18.04 with gnome 3.28.2, I had a problem with UP and LEFT when switching workspace.

Solved it, here is the commands:


gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['<Control><Alt>Left']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Control><Alt>Right']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['<Control><Alt>Up']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['<Control><Alt>Down']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left "['<Control><Shift><Alt>Left']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right "['<Control><Shift><Alt>Right']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up "['<Control><Shift><Alt>Up']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down "['<Control><Shift><Alt>Down']"

**Comment by zakkak** [comment]
Hello all, if you believe that the above belong in the readme of this extension please feel free to append them and open a PR.

Glad you've figured it out.
