### ISSUE TITLE
New release for 2.28

### ISSUE THREAD

**Issue by dLobatog** [zakkak/workspace-grid#68]
From what I saw, if I run:

`make`
`cp -r workspace-grid@mathematical.coffee.gmail.com ~/.local/share/gnome-shell/extensions/`

The plugin works again in 2.28. Without it, my desktop crashes in the worst way possible: it doesn't allow you to log in. After I upgraded to Fedora 28, I had to disable this extension on the console to be able to log in in the UI - I can see how a lot of users wouldn't be able to do this and they can get frustrated instead. 

A new release containing changes up to https://github.com/zakkak/workspace-grid/commit/757c2ea52044c8fa68278eb0581e0c16befd80da in the official website would be highly useful. 

Thanks @zakkak  - this is a great piece of software, I use it not just daily but every minute of my work day :smile:

**Comment by zakkak** [comment]
A new release has been rolled out both on github and extensions.gnome.org (still under review)
