### ISSUE TITLE
Bunch of noise/errors on syslog

### ISSUE THREAD

**Issue by gjm** [zakkak/workspace-grid#69]
Hi.

When i activate/deactivate overview i get a bunch a errors in syslog. Can't really make much of them so i don't know if it's just debug info or some error is happening. 

Here's a snippet: [https://pastebin.com/zCWngUs2](https://pastebin.com/zCWngUs2)

Tell me if there is anything i can do to help debug the issue.

Thanks in advance.

**Comment by zakkak** [comment]
Hi @gjm thanks for reporting this and sorry for not coming back earlier.
Please see #76
