### ISSUE TITLE
moving windows to other workspaces

### ISSUE THREAD

**Issue by oephi** [zakkak/workspace-grid#72]
I was running ubuntu and just today moved back to Arch on my machine.  In Ubuntu when pressing <shift><ctrl><alt> + arrow key, I could move the current window through any of the workspaces.  At the moment I can only move the window up and down the column with <shift><ctrl> + up/down.  The left and right isn't binded and I'm not sure where to do that.  Would that be a gsettings things for gnome.keybindings?

**Comment by zoltanmaric** [comment]
I'm using `workspace-grid` on Ubuntu 18.04, and until yesterday, I could move windows between workspaces with `Alt`+`Shift`+`Ctrl`+`arrow key` (just like the default shortcuts in Unity). Now this doesn't work any more (it just switches workspaces, not carrying the active window with it).

I checked the gnome keyboard shortcuts and found that there's a shortcut for moving the window between workspaces **up** and **down** with `Super` + `up/down arrow key`, but there's no entry for moving them left or right (because Gnome only has vertical workspace switching by default).

Where can we customize the shortcuts for `workspace-grid`? And what made them not work any more (or change)?

**Comment by zoltanmaric** [comment]
@oephi you can set those shortcuts with
```bash
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left "['<Control><Shift><Alt>Left']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right "['<Control><Shift><Alt>Right']"
```

**Comment by zoltanmaric** [comment]
I just checked the settings for `move-to-workspace-left` and `move-to-worskapce-right`, and they seem to be configured correctly:
```bash
→ gsettings get org.gnome.desktop.wm.keybindings move-to-workspace-left
['<Control><Shift><Alt>Left']
→ gsettings get org.gnome.desktop.wm.keybindings move-to-workspace-right
['<Control><Shift><Alt>Right']
```

but they still don't work.

**Comment by zoltanmaric** [comment]
My problem was that a recent update of grub (I believe) asked me to set a shortcut for changing the input source, and suggested `Alt`+`Shift` as the default option, which I accepted. This conflicted with my setting for moving windows between workspaces (`Ctrl`+`Shift`+`Alt`+`Arrow`).

I disabled the conflicting input switching shortcut in **Gnome Tweak Tool**:
`Keyboard & Mouse` > `Additional Layout Options` > `Switching to Another Layout` > (uncheck `Alt`+`Shift`).

**Comment by mohammadrafigh** [comment]
@zoltanmaric yes the same issue here and fixed by removing alt + shift shortcut for language layout.

**Comment by oephi** [comment]
@zoltanmaric that worked, thanks.  Already had something assigned to to that sequence so just removed the <alt> and it's golden.

**Comment by adarrra** [comment]
it works but it breaks the ability to switch language with alt+shift... How to have both?

**Comment by zoltanmaric** [comment]
@adarrra I don't think you can have both with overlapping shortcut keys. But for me, on Ubuntu, the default shortcut for switching languages has always been `Super`+`Space`, does that work for you?

**Comment by adarrra** [comment]
Yes, `super+space` works, but I used to alt+shift. 
 `alt+ctrl+shit+arrow` seems 2 keys differ from `alt+shift`,  why do they overlap each other?
Both shortcuts worked for me in Ubuntu 16 with unity

**Comment by zakkak** [comment]
This doesn't look like a bug of the extension. I am glad that you were able to pin it down and work-around it.
