### ISSUE TITLE
Alt-Tab between applications in different workspaces doesn't work

### ISSUE THREAD

**Issue by kfrncs** [zakkak/workspace-grid#79]
Title says it all. Super + Tab doesn't do it either.. Am I missing something?

Thanks

**Comment by zakkak** [comment]
Is this something working when the workspace-grid extension is disabled? It
doesn't sound like a bug related to the extension, more like a
configuration of the alt-tab behavior.

**Comment by kfrncs** [comment]
fixed it in dconf! org/gnome/shell/window-switcher/current-workspace-only

The issue arose when I enabled this plugin, I think. I'm not 100%

**Comment by zakkak** [comment]
To the best of my knowledge this plugin does not tamper with `org/gnome/shell/window-switcher/current-workspace-only`.

I am glad that you solved it and came back with the solution though. Thanks!
