### ISSUE TITLE
[Bug] Branch 3.30 makes gnome crash

### ISSUE THREAD

**Issue by TheBlackKoala** [zakkak/workspace-grid#87]
After having enabled the extension (as described in the bug thread noting that is doesn't work in 3.30 by metaphysical) the gnome-shell crashes on login.
I'm using arch with gnome 3.30.

**Comment by zakkak** [comment]
Please try with the latest 3.30 branch and report back.

**Comment by TheBlackKoala** [comment]
It has solved the problem :)

**Comment by thijzert** [comment]
Can confirm; it's stable across reboots too.
