### ISSUE TITLE
Overlay is missing anything but background [3.30]

### ISSUE THREAD

**Issue by TheBlackKoala** [zakkak/workspace-grid#97]
The only thing that shows up when shifting workspaces is the background (see screenshot).
Most importantly the indicator of where you are is missing.
![screenshot from 2018-10-04 19-01-02](https://user-images.githubusercontent.com/8694231/46490282-dfced300-c807-11e8-9a53-7054b86b685a.png)

**Comment by zakkak** [comment]
Please make sure you are using the latest version (you might need to `git pull --force`). I observed this behaviour while rebasing, but then I fixed it.

**Comment by TheBlackKoala** [comment]
A reboot cleared it up! Back on the workspacegrid! Love it! :D
