### ISSUE TITLE
ubuntu 18.10, grid is not working for secondary screen

### ISSUE THREAD

**Issue by eignatenkov** [zakkak/workspace-grid#98]
I have a laptop with additional monitor plugged in and after upgrading to Ubuntu 18.10 all is good on the main (laptop screen) but for the additional monitor all opened windows are displayed on every workspace.

**Comment by Chili-Man** [comment]
I'm running into this same exact issue but reversed; the laptop screen remains constant and additional monitor works; However, the animations are also off when moving horizontally  - it shows as if we were moving vertically.

**Comment by eignatenkov** [comment]
![screenshot from 2018-10-23 10-22-54](https://user-images.githubusercontent.com/7557238/47346524-ab835f80-d6ad-11e8-92b1-b8b2ca9f7388.png)
Actually, for me it turned out that the corresponding setting was reset after installation of 18.10.
